# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-18 04:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0004_auto_20160218_0843'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('description', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[(b'doing', b'Doing'), (b'finish', b'Finish')], default=b'doing', max_length=10)),
                ('updated_at', models.DateField(auto_now=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('subject', models.ManyToManyField(to='subjects.Subject')),
            ],
        ),
    ]
