# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-25 04:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_auto_20160225_1020'),
        ('tasks', '0004_auto_20160225_0833'),
    ]

    operations = [
    ]
