# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-25 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='subject',
            field=models.ManyToManyField(to='subjects.Subject'),
        ),
    ]
