# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-24 10:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_usercourse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercourse',
            old_name='subject',
            new_name='course',
        ),
    ]
