# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-25 03:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20160224_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercourse',
            name='is_active',
            field=models.CharField(default=b'0', max_length=10),
        ),
    ]
