# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-25 04:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_auto_20160225_0849'),
        ('courses', '0009_usercourse_is_active'),
    ]

    operations = [
    ]
