# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-25 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercourse',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
