# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-13 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('status', models.CharField(default=b'open', max_length=10)),
                ('created_at', models.DateField()),
                ('updated_at', models.DateField()),
                ('course', models.ManyToManyField(to='courses.Course')),
            ],
        ),
    ]
