# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-14 01:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
