# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-18 01:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0003_auto_20160121_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='status',
            field=models.CharField(choices=[(b'open', b'Opening'), (b'close', b'Closed')], default=b'open', max_length=10),
        ),
    ]
